#!/bin/bash

echo "Invoke initMysql.sh"

MYSQL_DB_HOST=${1}
MYSQL_DB_PORT=${2}
MYSQL_DB_USER=${3}
MYSQL_DB_PASSWORD=${4}
GRAFANA_DATABASE_NAME=${5}

INIT_DATA_SQL_FILE=${6}
echo "Param list: $MYSQL_DB_HOST   $MYSQL_DB_PORT  $MYSQL_DB_USER    $MYSQL_DB_PASSWORD   $GRAFANA_DATABASE_NAME  $INIT_DATA_SQL_FILE"

# Create the HUE database
mysql -u$MYSQL_DB_USER -p$MYSQL_DB_PASSWORD -P$MYSQL_DB_PORT -h$MYSQL_DB_HOST -e "CREATE DATABASE IF NOT EXISTS $GRAFANA_DATABASE_NAME"
mysql -u$MYSQL_DB_USER -p$MYSQL_DB_PASSWORD -P$MYSQL_DB_PORT -h$MYSQL_DB_HOST < $INIT_DATA_SQL_FILE