#!/bin/bash
host=$1
cmd="sudo python /usr/lib/python2.6/site-packages/ambari_agent/AmbariCleaner.py"

localUser="tencent"
loginUser="tencent"
loginPass="tencent"

sudo su ${localUser} -c "/var/lib/tbds-server/resources/scripts/execRemoteCmd.exp ${host} ${loginUser} ${loginPass} 3600 \"${cmd}\""
